version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev_2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: btm_learning
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_dev_2
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: spring_app_learning
    restart: always
    ports:
      - "8080:8088"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/btm_learning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

      # nếu bạn dùng profile
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data: